# Header

menu:
  主页: /
  随笔: /tags/随笔/
subtitle: 往事随风
description: 无名小辈
author: xiaoyu
email: kkewwei@163.com

# SubNava  可以链接到自己文章链接
subnav:
  github: "#"
  weibo: "#"
  rss: "#"
  #zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "kkewwei@163.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
url: https://kkewwei.github.io/elasticsearch_learning
root: /elasticsearch_learning/

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: true

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '谢谢阅读'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: 
# 微信二维码图片地址
weixin: 

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
#favicon: '/blob/master/img/picture.png'
favicon: '/elasticsearch_learning/img/ico.png'    #在主题的_config.yml里面配置图标是有效的, 这里没有效果
#favicon: 'http://owsl7963b.bkt.clouddn.com/ico.png'
#你的头像url   这个是github 代码的相对路径
avatar: '/blob/master/img/picture.jpg'
#avatar: 'http://owqu66xvx.bkt.clouddn.com/Free-Converter.com-timg-26972045.jpg'

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
gitment_owner: 'kkewwei'      #你的 GitHub ID
gitment_repo: 'comments'
#gitment_repo: 'kkewwei.github.io/comments'          #存储评论的 repo
#gitment_repo: 'kkewwei.github.io/elasticsearch_learning'
gitment_oauth:
  client_id: '9391e497d6b288887f33'           #client ID
  client_secret: 'db733731bff4ee2811d9530b1ac4cfc6767e8183'       #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

friends:
  友情链接1: http://localhost:4000/
#  友情链接2: http://localhost:4000/
#  友情链接3: http://localhost:4000/
#  友情链接4: http://localhost:4000/
#  友情链接5: http://localhost:4000/
#  友情链接6: http://localhost:4000/

aboutme: 往事随风<br><br>当才华满足不了你的梦想的时候，你就应该好好学习

theme: yilia

deploy:
  type: git
  repo: git@github.com:kkewwei/elasticsearch_learning.git
  branch: master
  message: do it

jsonContent:
    meta: false
    pages: false
    posts:
      title: true
      date: true
      path: true
      text: false
      raw: false
      content: false
      slug: false
      updated: false
      comments: false
      link: false
      permalink: false
      excerpt: false
      categories: false
      tags: true

sitemap:
    path: sitemap.xml

post_asset_folder: true